### ISSUE TITLE
Git Host Support Tracker

### ISSUE THREAD

**Issue by mterlyn** [schmayterling/comment-issues#3]
> **Disclaimer**
> Comment Issues should work under any git host that puts issues under the `domain.tld/<user>/<repo>/issues/#` endpoint. (also works with ssh repos)

## Working (Tested)
- [x] GitHub - v1.0.0 (hardcoded/default)
- [x] GitLab - v1.0.0 (hardcoded)
- [x] Bitbucket - v1.0.0 (hardcoded/default)
- [x] All Forgejo instances - v1.0.0 (default)
- [x] All Gitea instances - v1.0.0 (default)
- Please feel free to report working git hosts in this thread!
## Broken
- N/A, please open an issue if theres any not working!
