### ISSUE TITLE
Language Support Tracker

### ISSUE THREAD

**Issue by mterlyn** [schmayterling/comment-issues#4]
> **Disclaimer**
> Comment Issues should theoretically support any languages with the following comment syntax. `#`, `//` `/* */`, `*`, `--`, `%`

## Working (Tested)
- [x] Javascript - tested by me
- [x] Typescript - tested by me
- [x] Rust - tested by me
- Please feel free to report working languages in this thread!

## Broken
- N/A, please report if any!
